/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    BankCard: typeof import('./src/components/order/BankCard.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    CopyIcon: typeof import('./src/components/ui/icons/CopyIcon.vue')['default']
    Drawer: typeof import('./src/components/ui/drawer/Drawer.vue')['default']
    DrawerContent: typeof import('./src/components/ui/drawer/DrawerContent.vue')['default']
    DrawerDescription: typeof import('./src/components/ui/drawer/DrawerDescription.vue')['default']
    DrawerFooter: typeof import('./src/components/ui/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./src/components/ui/drawer/DrawerHeader.vue')['default']
    DrawerOverlay: typeof import('./src/components/ui/drawer/DrawerOverlay.vue')['default']
    DrawerTitle: typeof import('./src/components/ui/drawer/DrawerTitle.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IndividualPayment: typeof import('./src/components/order/IndividualPayment.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    OrderCardInstruction: typeof import('./src/components/order/OrderCardInstruction.vue')['default']
    ProductsMockList: typeof import('./src/components/products/ProductsMockList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./src/components/ui/textarea/Textarea.vue')['default']
  }
}
