services:
    nginx:
        image: nginx:stable-alpine
        container_name: twa-nginx
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
